### ISSUE TITLE
Examples of how you use a model?

### ISSUE THREAD

**Issue by oliver-batchelor** [buckbaskin/formak#27]
# Feature Request

Saw this project and it looks really neat - but some more introductory material would be great. 

For example the demo "demos/src/orbital_model.py" creates a model but lacks any actual use of the model. Can you use the model to perform Kalman filtering directly? 

Is this library for optimising trajectories or for doing online state estimation type tasks?

**Comment by buckbaskin** [comment]
@oliver-batchelor Thanks for opening an issue. 

> Saw this project and it looks really neat - but some more introductory material would be great.

I agree that more introductory material will be helpful, let me see what I can do.
I think the material may be available in the repository but spread out in a way that's harder to find.

> For example the demo "demos/src/orbital_model.py" creates a model but lacks any actual use of the model. Can you use the model to perform Kalman filtering directly?

The model in the example `demos/src/orbital_model.py` is a symbolic Python model. The intended use case is to compile the symbolic model to either a Python or a C++ implementation (or both) to perform the Kalman filtering.
(I'll update the documentation to reflect this as well)

> Is this library for optimising trajectories or for doing online state estimation type tasks?

The original intent of the library is to focus on online state estimation
